# Generated by Django 5.0.7 on 2024-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="topic_aim",
            field=models.CharField(default="", max_length=200),
        ),
    ]
