# Generated by Django 5.0.7 on 2024-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dairy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dairyitem",
            name="topic",
            field=models.CharField(default="无题", max_length=40),
        ),
    ]
