# Generated by Django 5.0.7 on 2024-07-15 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dairy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dairy_item",
            name="mood",
        ),
    ]
